Adding scrubs to the MediDrobe
DeltaV-Station/Delta-v-Legacy pull request #129
Opened 2023-08-15 08:17 UTC by evilexecutive

## About the PR

This adds all three scrub colors to the MediDrobe. Which guarantees that people who prefer the scrubs will be able to get them in every map(As opposed to random chance via the lockers)

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- Scrubs can now be obtained from the MediDrobe

2023-08-15 08:23 UTC, Colin-Tel commented
Don't forget to format the changelog so that it says "add:" or "tweak:" after the bullet but before the change.

2023-08-15 08:26 UTC, DEATHB4DEFEAT requested changes
Why is the entire file a diff? GitHub moment? :godmode:

2023-08-15 08:26 UTC, DEATHB4DEFEAT commented on Resources/Prototypes/Catalog/VendingMachines/Inventories/medidrobe.yml
> +s- type: vendingMachineInventory
```suggestion
- type: vendingMachineInventory
```

2023-08-15 08:26 UTC, evilexecutive commented
Oh thanks for the heads up!

2023-08-15 08:27 UTC, Colin-Tel commented on Resources/Prototypes/Catalog/VendingMachines/Inventories/medidrobe.yml
> +s- type: vendingMachineInventory
Could it be because he's making his changes on his master? 🤔

2023-08-15 08:28 UTC, DEATHB4DEFEAT commented on Resources/Prototypes/Catalog/VendingMachines/Inventories/medidrobe.yml
> +s- type: vendingMachineInventory
> Could it be because he's making his changes on his master? 🤔

:goberserk:

2023-08-15 08:29 UTC, evilexecutive commented on Resources/Prototypes/Catalog/VendingMachines/Inventories/medidrobe.yml
> +s- type: vendingMachineInventory
Wait is that a problem?

2023-08-15 08:29 UTC, evilexecutive commented on Resources/Prototypes/Catalog/VendingMachines/Inventories/medidrobe.yml
> +s- type: vendingMachineInventory
Sorry, I am very much a newb at github.

2023-08-15 09:24 UTC, DEATHB4DEFEAT commented on Resources/Prototypes/Catalog/VendingMachines/Inventories/medidrobe.yml
> +    ClothingHeadNurseHat: 4
Was missing in the new diff
```suggestion
    ClothingHeadNurseHat: 4
    ClothingUniformJumpskirtNurse: 4
```

2023-08-15 09:27 UTC, DEATHB4DEFEAT commented
> > > Could it be because he's making his changes on his master? 🤔
> >
> > :goberserk:
> 
> Wait is that a problem?

PRing from the `master` branch doesn't allow you to make any other PR without having changes from that modified master branch unless you use the CLI to branch off of a remote master
You should make "feature branches" and leave `master` untouched, only using it to keep up to date with the remote master for branching off of, consider `master` the "stable" or release branch

2023-08-15 09:59 UTC, evilexecutive commented
> PRing from the `master` branch doesn't allow you to make any other PR without having changes from that modified master branch unless you use the CLI to branch off of a remote master You should make "feature branches" and leave `master` untouched, only using it to keep up to date with the remote master for branching off of, consider `master` the "stable" or release branch

Oh, this just means I can only have  one PR open if I'm doing it off a master branch? That's fine for now, seeing as I don't have anything else to PR for the forseable future. How can I make feature branches in the future?

2023-08-15 10:39 UTC, Colin-Tel commented
> Oh, this just means I can only have one PR open if I'm doing it off a master branch? That's fine for now, seeing as I don't have anything else to PR for the forseable future. How can I make feature branches in the future?

Just make a branch based off "master" and make your changes on that. That way master remains untouched.

2023-08-17 02:47 UTC, DebugOk commented
Please dont PR from master

2023-08-17 02:47 UTC, closed without merging

2023-08-17 15:29 UTC, VMSolidus commented
Okay, so can you explain to me how I can make one of these "Feature Forks"?