Updated Emergency Lockers to contain Nitrogen tanks
DeltaV-Station/Delta-v-Legacy pull request #130
Opened 2023-08-15 10:20 UTC by DangerRevoltion

## About the PR

Added standard Nitrogen Tanks to emergency lockers so Slimes are able to make use of them, currently; should an area be spaced Slimes are not accounted for regarding emergency lockers and so if they do not have a nitrogen tank on them, they are doomed.

**Media**

- [X ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Danger!Revolution!
- add: Added Nitrogen Tanks to Emergency Lockers

2023-08-15 10:42 UTC, Colin-Tel commented
It's kind of dumb there aren't any "emergency" air/n2 tanks, because that would really come in handy here.

2023-08-15 10:50 UTC, DangerRevoltion commented
> It's kind of dumb there aren't any "emergency" air/n2 tanks, because that would really come in handy here.

I am actually working on that now; I've got a working emergency N2 tank, I'm just recolouring the emergency O2 tank sprites now :)

2023-08-15 12:35 UTC, DangerRevoltion commented on Resources/Prototypes/Entities/Objects/Tools/gas_tanks.yml
> +# I've tried to look into it and I can't see why setting the emergency nitrogen tank to
still looking into this.

2023-08-15 12:36 UTC, DangerRevoltion commented on Resources/Prototypes/Entities/Objects/Tools/gas_tanks.yml
> +
still looking into this.

2023-08-15 19:40 UTC, DebugOk requested changes
It might be better to have the oxygen and nitrogen tanks in the same or group, then tweak the probabilities a little.

As an example
Full oxygen - 0.5
Full nitrogen - 0.3
Emergency oxygen - 0.10
Emergency nitrogen - 0.10

2023-08-15 21:33 UTC, DangerRevoltion commented
Does this not cause issues by randomising the viability of emergency lockers?
My interpretation of your suggestion was to make
- emergency oxygen tank
- oxygen tank
- emergency nitrogen tank
- nitrogen tank
all mutually exclusive in the loot table?
Hence: you, as a human, could now walk up to an emergency locker and potentially find a nitrogen tank in there; creating a new problem?
or: a slime could walk up to an emergency locker and STILL not find Nitrogen despite the fix?

2023-08-15 21:51 UTC, DebugOk commented
> Does this not cause issues by randomising the viability of emergency lockers?
> My interpretation of your suggestion was to make
> - emergency oxygen tank
> - oxygen tank
> - emergency nitrogen tank
> - nitrogen tank
> all mutually exclusive in the loot table?
> Hence: you, as a human, could now walk up to an emergency locker and potentially find a nitrogen tank in there; creating a new problem?
> or: a slime could walk up to an emergency locker and STILL not find Nitrogen despite the fix?

I can see this getting abused, but eh, should be fine as is then. It'd be less of an issue of slimes started with the proper tank

2023-08-31 12:22 UTC, DebugOk approved these changes

2023-09-09 13:24 UTC, DebugOk commented
You dont need to keep merging master

2023-12-05 00:52 UTC, closed without merging