Siobhan, Mystagogue's Arctic Fox
DeltaV-Station/Delta-v-Legacy pull request #171
Opened 2023-09-06 06:57 UTC by TadJohnson00

## About the PR

Adds Siobhan, the Mystagogue's arctic fox, as well as Rennie and Shivs toys.

**Media**

![image](https://github.com/DeltaV-Station/Delta-v/assets/120885811/3df4e4f2-2f94-4296-b089-796bceb9b87e)

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added arctic foxes to the game. Who knows, maybe you'll see one around!

2023-09-06 07:15 UTC, TadJohnson00 commented
Ayyy greentext first try

2023-09-09 09:05 UTC, DEATHB4DEFEAT commented
The sprite reminded me of what I did to McGriff, so I did the same to this :)

![mcg](https://github.com/DeltaV-Station/Delta-v/assets/77995199/a38f6c3b-79a5-4273-8dd2-d62ff5af08cb)

2023-09-09 09:07 UTC, DEATHB4DEFEAT requested changes

2023-09-09 09:07 UTC, DEATHB4DEFEAT commented on Resources/Prototypes/DeltaV/Entities/Markers/Spawners/mobs.yml
> +  name: Arctic Fox Siobhan Spawner
Isn't the other spawners' format something like `name: <animal> spawner` with `suffix: <pet name>`?
You're also missing generic arctic fox spawner

2023-09-09 09:07 UTC, DEATHB4DEFEAT commented on Resources/Prototypes/DeltaV/Entities/Mobs/NPCs/animals.yml
> +  description: They're a fox, of the arctic variety.
This is lame, consider making some joke about them.

2023-09-09 09:07 UTC, DEATHB4DEFEAT commented on Resources/Prototypes/DeltaV/Entities/Objects/Fun/toys.yml
> +  name: rennie toy
```suggestion
  name: renault toy
```

2023-09-09 09:07 UTC, DEATHB4DEFEAT commented on Resources/Prototypes/DeltaV/Entities/Objects/Fun/toys.yml
> +  name: shivs toy
```suggestion
  name: siobhan toy
```

2023-09-09 09:31 UTC, TadJohnson00 commented on Resources/Prototypes/DeltaV/Entities/Markers/Spawners/mobs.yml
> +  name: Arctic Fox Siobhan Spawner
Let me double check, and add a generic arctic fox spawner

2023-09-09 09:31 UTC, TadJohnson00 commented on Resources/Prototypes/DeltaV/Entities/Mobs/NPCs/animals.yml
> +  description: They're a fox, of the arctic variety.
It was going to be a placeholder, I just forgot to change it

2023-09-09 09:34 UTC, TadJohnson00 commented on Resources/Prototypes/DeltaV/Entities/Markers/Spawners/mobs.yml
> +  name: Arctic Fox Siobhan Spawner
Nope, as far as I can see it follows a [Animal Type] [Name] Spawner (e.g. Fox Renault Spawner)

2023-09-09 09:38 UTC, TadJohnson00 commented on Resources/Prototypes/DeltaV/Entities/Markers/Spawners/mobs.yml
> +  name: Arctic Fox Siobhan Spawner
Scratch that, I'm not going to add a generic arctic fox spawner, there's no other generic animal spawners that I can see, with the exception of the random cat spawner and maybe one or two others.

2023-09-09 09:48 UTC, TadJohnson00 commented
Just to let you know, I was considering putting one or two bluespace crystals inside Shivs, but decided against it due to balance reasons... but then again, what sick fuck would butcher their own pet just for a measly couple of crystals?

2023-09-09 13:27 UTC, DebugOk commented
Looks good enough, good luck mapping it though :clueless:

2023-09-09 13:27 UTC, merged