New hairstyle! Short bedhead.
DeltaV-Station/Delta-v-Legacy pull request #173
Opened 2023-09-08 18:56 UTC by Adrian16199

A new barber has arrived and made a new hairstyle for people to go for!

## About the PR

Adds new hairstyle into the game: Short bedhead.

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: A new barber has been seen nearby of your station! Seems to have a new hairstyle to show.

2023-09-08 21:36 UTC, DEATHB4DEFEAT requested changes

2023-09-08 21:36 UTC, DEATHB4DEFEAT commented on Resources/Textures/DeltaV/Mobs/Customization/new_hair.rsi/meta.json
JSON minifying makes conflicts and future reviews much harder, format this readably

2023-09-09 07:42 UTC, Adrian16199 commented on Resources/Textures/DeltaV/Mobs/Customization/new_hair.rsi/meta.json
Like this?

2023-09-09 08:23 UTC, DEATHB4DEFEAT commented on Resources/Textures/DeltaV/Mobs/Customization/new_hair.rsi/meta.json
yeah

2023-09-09 08:24 UTC, DEATHB4DEFEAT commented on Resources/Textures/DeltaV/Mobs/Customization/new_hair.rsi/meta.json
> +}
```suggestion
}

```

2023-09-09 08:24 UTC, DEATHB4DEFEAT approved these changes

2023-09-09 08:47 UTC, Adrian16199 commented
Is there a particular reason why it failed "Build & Test Debug / build (windows-latest) (pull_request)"?

2023-09-09 09:08 UTC, DEATHB4DEFEAT commented
> Is there a particular reason why it failed "Build & Test Debug / build (windows-latest) (pull_request)"?

not related

2023-09-09 13:32 UTC, DebugOk commented
> * I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

Where?

2023-09-09 13:34 UTC, Adrian16199 commented
> > * I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
> 
> Where?

I did include a png while makin this post but its not appearing and i have no idea why.

2023-09-09 13:37 UTC, Adrian16199 commented
Hopefully it says now that i did not include any screenshots and such so there is no more issues.

2023-09-09 13:38 UTC, merged