Butlertron, the Roboisseur
DeltaV-Station/Delta-v-Legacy pull request #193
Opened 2023-09-20 20:57 UTC by PHCodes

"Greetings meatbags!

This is Butlertron_Durandal, the latest in entrepreneurship technology! I have heard word that you all staff an exorbiant number of fleshlings to prepare food and drink aboard your stations. With my latest contract with your station owners, I am prepared and willing to deploy terminals to every station in the cosmos! I hope you all are ready, because there is a great deal of money to be made if you can source the dishes my discerning clientele desire."

Implements the new entity type 'Mr. Butlertron'. Mr. Butlertron requests specific foods from players, using the list of recipes available to the game. He has a blacklist of items he will not request, which fundamentally make up three categories: Simple, Disgusting, and Cannibalistic. He also has 3 tiers of foods he can request, and could be iterated upon in the future to add more tiers. Each tier increases the amount of zorkmids he will give in payment, and from the 2nd tier of food onward, he will dispense ice cream along with his dough. Take too long, however, and this affable automaton will begin to become upset, and may even lose his temper entirely, changing his request to something new. This change occurs after 10 minutes, and he begins getting impatient after 8 minutes have passed. I reused several of the scripts used by the Oracle to create Mr. Butlertron, and am hoping in the future to make him a roaming NPC, perhaps by splitting up his responsibilities into different chunks and having different 'styles' of Mr. Butlertron being able to spawn on different stations. Given that Delta-V does not have a significant amount of its own unique content and folders to support that unique content, I placed most of his files within Nyano's files.

Maybe this is not how it should be structure, and I open to suggestions.

## About the PR

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added Mr. Butlertron, the Roboisseur

2023-09-20 23:58 UTC, DEATHB4DEFEAT requested changes
What a cool sounding feature 👍

2023-09-20 23:58 UTC, DEATHB4DEFEAT commented on Content.Server/Nyanotrasen/Roboisseur/RoboisseurComponent.cs
> +}
```suggestion
}

```

2023-09-20 23:58 UTC, DEATHB4DEFEAT commented on Content.Server/Nyanotrasen/Roboisseur/RoboisseurSystem.cs
> +}
```suggestion
}

```

2023-09-20 23:58 UTC, DEATHB4DEFEAT commented on Resources/Locale/en-US/roboisseur/roboisseur.ftl
> +roboisseur-deny-3 = Not what the client's looking for.
```suggestion
roboisseur-deny-3 = Not what the client's looking for.

```

2023-09-20 23:58 UTC, DEATHB4DEFEAT commented on Resources/Prototypes/Nyanotrasen/Entities/Structures/Machines/roboisseur.yml
> +    tags: []
```suggestion
    tags: []

```

2023-09-20 23:58 UTC, DEATHB4DEFEAT commented on Resources/Textures/DeltaV/Structures/Machines/roboisseur.rsi/meta.json
> +}
```suggestion
}

```

2023-09-20 23:58 UTC, DEATHB4DEFEAT commented on Content.Server/Nyanotrasen/Roboisseur/RoboisseurSystem.cs
> +    }
Odd placement for this, I'd have it near the bottom with a newline or two between it and whatever else is around it

2023-09-20 23:58 UTC, DEATHB4DEFEAT commented on Content.Server/Nyanotrasen/Roboisseur/RoboisseurSystem.cs
> +        [ViewVariables(VVAccess.ReadWrite)]
What is this doing in a system?

2023-09-20 23:58 UTC, DEATHB4DEFEAT commented on Content.Server/Nyanotrasen/Roboisseur/RoboisseurSystem.cs
> +        };
This should probably all be in the component as defaults instead of readonly in a system.

2023-09-20 23:58 UTC, DEATHB4DEFEAT commented on Content.Server/Nyanotrasen/Roboisseur/RoboisseurSystem.cs
> +        }
```suggestion
        }


```

2023-09-20 23:58 UTC, DEATHB4DEFEAT commented on Content.Server/Nyanotrasen/Roboisseur/RoboisseurSystem.cs
> +            Random r = new Random();
Haven't seen this Type before, I normally use the robust random system dependency.
```suggestion
            var r = new Random();
```

2023-09-20 23:58 UTC, DEATHB4DEFEAT commented on Content.Server/Nyanotrasen/Roboisseur/RoboisseurSystem.cs
> +            if(tier > 1){
```suggestion
            if(tier > 1)
            {
```

2023-09-20 23:58 UTC, DEATHB4DEFEAT commented on Content.Server/Nyanotrasen/Roboisseur/RoboisseurSystem.cs
> +                return;
```suggestion
                return;

```

2023-09-20 23:58 UTC, DEATHB4DEFEAT commented on Content.Server/Nyanotrasen/Roboisseur/RoboisseurSystem.cs
> +                message = Loc.GetString(_random.Pick(DemandMessagesTier2), ("item", component.DesiredPrototype.Name));
```suggestion
                message = Loc.GetString(_random.Pick(DemandMessagesTier2), ("item", component.DesiredPrototype.Name));

```

2023-09-20 23:58 UTC, DEATHB4DEFEAT commented on Content.Server/Nyanotrasen/Roboisseur/RoboisseurSystem.cs
> +                return;
I don't see a reason for MobStateComponent to be checked here, remove it if there isn't a reason.

`MetaDataComponent` and `TransformComponent` are always on every entity, there is no need for a TryGet or HasComp. Getting these two components can also be done via functions in the system, `MetaData(EntityUid)` and `Transform(EntityUid)` respectively.
```suggestion
            if (HasComp<MobStateComponent>(args.Used) ||
                MetaData(args.Used)?.EntityPrototype == null)
                return;
```

2023-09-20 23:58 UTC, DEATHB4DEFEAT commented on Content.Server/Nyanotrasen/Roboisseur/RoboisseurSystem.cs
> +
```suggestion
```

2023-09-20 23:58 UTC, DEATHB4DEFEAT commented on Content.Server/Nyanotrasen/Roboisseur/RoboisseurSystem.cs
> +            RewardServicer(args.User, component, tier);
```suggestion
            if (!validItem)
            {
                _chat.TrySendInGameICMessage(uid, Loc.GetString(_random.Pick(RejectMessages)), InGameICChatType.Speak, true);
                return;
            }

            component.Impatient = false;
            EntityManager.QueueDeleteEntity(args.Used);

            int tier = CheckTier(component.DesiredPrototype.ID);

            string message = Loc.GetString(_random.Pick(RewardMessages));
            if (tier > 1)
                message = Loc.GetString(_random.Pick(RewardMessagesTier2));
            _chat.TrySendInGameICMessage(uid, message, InGameICChatType.Speak, true);

            RewardServicer(args.User, component, tier);
```

2023-09-20 23:58 UTC, DEATHB4DEFEAT commented on Content.Server/Nyanotrasen/Roboisseur/RoboisseurSystem.cs
> +        private bool CheckValidity(EntityPrototype given, EntityPrototype target)
```suggestion

        private bool CheckValidity(EntityPrototype given, EntityPrototype target)
```

2023-09-20 23:58 UTC, DEATHB4DEFEAT commented on Content.Server/Nyanotrasen/Roboisseur/RoboisseurSystem.cs
> +        private int CheckTier(String target)
```suggestion

        private int CheckTier(String target)
```

2023-09-20 23:58 UTC, DEATHB4DEFEAT commented on Content.Server/Nyanotrasen/Roboisseur/RoboisseurSystem.cs
> +            if (_prototypeManager.TryIndex<EntityPrototype>(protoString, out var proto))
```suggestion

            if (_prototypeManager.TryIndex<EntityPrototype>(protoString, out var proto))
```

2023-09-20 23:58 UTC, DEATHB4DEFEAT commented on Content.Server/Nyanotrasen/Roboisseur/RoboisseurSystem.cs
> +                _sawmill.Error("Oracle can't index prototype " + protoString);
```suggestion
                _sawmill.Error("Roboisseur can't index prototype " + protoString);
```

2023-09-20 23:58 UTC, DEATHB4DEFEAT commented on Content.Server/Nyanotrasen/Roboisseur/RoboisseurSystem.cs
> +        public List<string> GetAllProtos()
```suggestion

        public List<string> GetAllProtos()
```

2023-09-20 23:58 UTC, DEATHB4DEFEAT commented on Content.Server/Nyanotrasen/Roboisseur/RoboisseurSystem.cs
> +
```suggestion
```

2023-09-20 23:58 UTC, DEATHB4DEFEAT commented on Content.Server/Nyanotrasen/Roboisseur/RoboisseurSystem.cs
> +            return allProtos;
```suggestion
            foreach (var recipe in allRecipes)
                allProtos.Add(recipe.Result);

            foreach (var proto in BlacklistedProtos)
                allProtos.Remove(proto);

            return allProtos;
```

2023-09-20 23:58 UTC, DEATHB4DEFEAT commented on Content.Server/Nyanotrasen/Roboisseur/RoboisseurSystem.cs
> +        private readonly ISawmill _sawmill = default!;
Use the system-wide `Log` function (I think that's what it's called now?)
```suggestion
```

2023-09-20 23:58 UTC, DEATHB4DEFEAT commented on Content.Server/Nyanotrasen/Roboisseur/RoboisseurComponent.cs
> +
```suggestion
```

2023-09-20 23:58 UTC, DEATHB4DEFEAT commented on Resources/Prototypes/Nyanotrasen/Entities/Structures/Machines/roboisseur.yml
> +    offset: "0.0,0.5"
Why's it offset?

```suggestion
    offset: 0.0, 0.5
```

2023-09-21 00:01 UTC, DEATHB4DEFEAT commented
Should create some media for the PR description.

2023-09-21 00:02 UTC, DEATHB4DEFEAT requested changes
I forgot to check namespaces; move the component, system, locale, and yml to the DeltaV subfolder folder.

2023-09-21 00:20 UTC, leonardo-dabepis commented on Resources/Prototypes/Nyanotrasen/Entities/Structures/Machines/roboisseur.yml
> +  description: It asks for food to deliver to exotic customers across the cosmos. Maybe it's got a Psionic teleporter?
the "maybe it's got a psionic teleporter?" seems out of place and doesn't really make sense in this context. Should probably be something like "Powered by the latest technology in bluespace food delivery". At least that's just my opinion 🤪

2023-09-21 02:34 UTC, PHCodes commented on Resources/Prototypes/Nyanotrasen/Entities/Structures/Machines/roboisseur.yml
> +  description: It asks for food to deliver to exotic customers across the cosmos. Maybe it's got a Psionic teleporter?
The idea was to give some bad reason to why it can't be e-magged, at least not yet. Will change to your suggestion since as far as I know bluespace items also cannot be e-magged.

2023-09-21 03:17 UTC, PHCodes commented on Resources/Prototypes/Nyanotrasen/Entities/Structures/Machines/roboisseur.yml
> +  description: It asks for food to deliver to exotic customers across the cosmos. Maybe it's got a Psionic teleporter?
Fixed. I bet you like Midochlorians, too.

2023-09-21 03:17 UTC, PHCodes commented on Content.Server/Nyanotrasen/Roboisseur/RoboisseurSystem.cs
> +        };
Moved.

2023-09-21 05:32 UTC, DEATHB4DEFEAT requested changes
Grammar is fun.

2023-09-21 05:32 UTC, DEATHB4DEFEAT commented on Content.Server/DeltaV/NPC/Roboisseur/RoboisseurComponent.cs
> +        };
Needs datafield tags and remove the readonlys

2023-09-21 05:32 UTC, DEATHB4DEFEAT commented on Content.Server/DeltaV/NPC/Roboisseur/RoboisseurSystem.cs
> +        public override void Initialize()
```suggestion
        [Dependency] private readonly AppearanceSystem _appearance = default!;


        public override void Initialize()
```

2023-09-21 05:32 UTC, DEATHB4DEFEAT commented on Content.Server/DeltaV/NPC/Roboisseur/RoboisseurSystem.cs
> +            SubscribeLocalEvent<RoboisseurComponent, ComponentInit>(OnInit);
```suggestion
            base.Initialize();


            SubscribeLocalEvent<RoboisseurComponent, ComponentInit>(OnInit);
```

2023-09-21 05:32 UTC, DEATHB4DEFEAT commented on Content.Server/DeltaV/NPC/Roboisseur/RoboisseurSystem.cs
> +            foreach (var roboisseur in EntityQuery<RoboisseurComponent>())
```suggestion
            base.Update(frameTime);


            foreach (var roboisseur in EntityQuery<RoboisseurComponent>())
```

2023-09-21 05:32 UTC, DEATHB4DEFEAT commented on Content.Server/DeltaV/NPC/Roboisseur/RoboisseurSystem.cs
> +    public enum RobossieurVisualLayers : byte
```suggestion
    }

    public enum RobossieurVisualLayers : byte
```

2023-09-21 05:32 UTC, DEATHB4DEFEAT commented on Resources/Locale/en-US/deltav/roboisseur/roboisseur.ftl
> +roboisseur-request-4 = My more... Adventurous Clients require a {$item}.
```suggestion
roboisseur-request-4 = My more... Adventurous Clients require {INDEFINITE($item)} {$item}.
```

2023-09-21 05:32 UTC, DEATHB4DEFEAT commented on Resources/Locale/en-US/deltav/roboisseur/roboisseur.ftl
> +roboisseur-request-3 = There may be an exorbiantly affluent personage in this sector looking for a {$item}.
```suggestion
roboisseur-request-3 = There may be an exorbitantly affluent personage in this sector looking for {INDEFINITE($item)} {$item}.
```

2023-09-21 05:32 UTC, DEATHB4DEFEAT commented on Resources/Locale/en-US/deltav/roboisseur/roboisseur.ftl
> +roboisseur-request-impatient-3 = Damn you all! Deliver me a {$item} already!
```suggestion
roboisseur-request-impatient-3 = Damn you all! Deliver me {INDEFINITE($item)} {$item} already!
```

2023-09-21 05:32 UTC, DEATHB4DEFEAT commented on Resources/Locale/en-US/deltav/roboisseur/roboisseur.ftl
> +roboisseur-request-second-2 = The frozen planet in this sector requests a {$item}!
```suggestion
roboisseur-request-second-2 = The frozen planet in this sector requests {INDEFINITE($item)} {$item}!
```

2023-09-21 05:32 UTC, DEATHB4DEFEAT commented on Resources/Locale/en-US/deltav/roboisseur/roboisseur.ftl
> +roboisseur-request-second-3 = A local ice cream vendor is looking to trade for a {$item}.
```suggestion
roboisseur-request-second-3 = A local ice cream vendor is looking to trade for {INDEFINITE($item)} {$item}.
```

2023-09-21 05:32 UTC, DEATHB4DEFEAT commented on Resources/Locale/en-US/deltav/roboisseur/roboisseur.ftl
> +roboisseur-request-impatient-2 = My market opportunity is dwindling! Quickly, you fools, {$item}!
```suggestion
roboisseur-request-impatient-2 = My market opportunity is dwindling! Quickly, you fools, {THE($item)}!
```

2023-09-21 05:32 UTC, DEATHB4DEFEAT commented on Resources/Locale/en-US/deltav/roboisseur/roboisseur.ftl
> +roboisseur-request-impatient-1 = There is no time left! Bring me {$item}, immediately!
```suggestion
roboisseur-request-impatient-1 = There is no time left! Bring me {THE($item)}, immediately!
```

2023-09-21 05:32 UTC, DEATHB4DEFEAT commented on Resources/Locale/en-US/deltav/roboisseur/roboisseur.ftl
> +roboisseur-request-6 = Local changes in this quadrant's stock exchange decteted. Seeking {$item}.
```suggestion
roboisseur-request-6 = Local changes in this quadrant's stock exchange decteted. Seeking {INDEFINITE($item)} {$item}.
```

2023-09-21 05:32 UTC, DEATHB4DEFEAT commented on Resources/Locale/en-US/deltav/roboisseur/roboisseur.ftl
I didn't test these suggested changes but they should work as intended, make sure for me :)

2023-09-21 05:32 UTC, DEATHB4DEFEAT commented on Resources/Prototypes/DeltaV/NPC/roboisseur.yml
> +    offset: 0.0, 0.0
```suggestion
```

2023-09-21 05:32 UTC, DEATHB4DEFEAT commented on Resources/Prototypes/DeltaV/NPC/roboisseur.yml
> +    tags: []
Is there a tag on the base you are removing or can this component be removed?

2023-09-21 13:18 UTC, PHCodes commented on Content.Server/DeltaV/NPC/Roboisseur/RoboisseurComponent.cs
> +        };
Added and removed.

2023-09-21 13:18 UTC, PHCodes commented on Resources/Locale/en-US/deltav/roboisseur/roboisseur.ftl
Testing...

2023-09-21 13:18 UTC, PHCodes commented on Resources/Prototypes/DeltaV/NPC/roboisseur.yml
> +    tags: []
Don't know why you call it a component, but I have removed the type and sprite fade tags. Don't really need them on Mr. Butlertron.

2023-09-21 13:23 UTC, PHCodes commented on Resources/Locale/en-US/deltav/roboisseur/roboisseur.ftl
Works.

2023-09-21 16:00 UTC, DEATHB4DEFEAT approved these changes

2023-09-22 03:04 UTC, merged