Adding a small part of the ghost bar system early
DeltaV-Station/Delta-v-Legacy pull request #51
Opened 2023-06-01 17:26 UTC by DebugOk

Really just a spawner, not much to it.

2023-06-01 22:22 UTC, DEATHB4DEFEAT commented
since players can't select a different character slot mid-round I think prompting with a list of their characters when taking the role would be cool.

2023-06-01 22:23 UTC, DebugOk commented
> since players can't select a different character slot mid-round I think prompting with a list of their characters when taking the role would be cool.

While this would be possible, this is just a small part of another system I'm working. But it might still be good to implement something like that. I'll look into it

2023-06-01 23:19 UTC, DEATHB4DEFEAT commented on Content.Server/DeltaV/Humanoid/Systems/LoadHumanoidSystem.cs
> +        }
suggestion is a bit wonky but these two ifs could be combined
```suggestion
        
        if (// Character has no mind, so we cant import their preferences
            !TryComp<MindComponent>(uid, out var mindComponent) ||
            mindComponent.Mind?.UserId == null ||
            // There is already a profile present, if we continue we may delete something unintended
            !TryComp(uid, out HumanoidAppearanceComponent? humanoid) ||
            !string.IsNullOrEmpty(humanoid.Initial))
            return; 
```

2023-06-01 23:19 UTC, DEATHB4DEFEAT commented on Content.Server/DeltaV/Humanoid/Systems/LoadHumanoidSystem.cs
> +            .SpawnPlayerMob(coordinates: coordinates, profile: character, entity: null, job: null, station: null);
does each argument *need* to specify the variable to assign to?

2023-06-01 23:19 UTC, DEATHB4DEFEAT commented on Content.Server/DeltaV/Humanoid/Systems/LoadHumanoidSystem.cs
> +        var mind = mindComponent.Mind;
seems this is only used twice, could rename `mindComponent` to `mind` and use `mind.Mind` elsewhere instead

2023-06-01 23:19 UTC, DEATHB4DEFEAT commented on Resources/Prototypes/DeltaV/Entities/Markers/Spawners/ghost_roles.yml
> +      rules: Listen to the admins.
> Listen to the admins

What if there are no admins? And how should the admins communicate the rules to them?

2023-06-02 06:18 UTC, DebugOk commented on Content.Server/DeltaV/Humanoid/Systems/LoadHumanoidSystem.cs
> +            .SpawnPlayerMob(coordinates: coordinates, profile: character, entity: null, job: null, station: null);
During my testing, yes, it was showing these an non optional

2023-06-02 06:46 UTC, DebugOk commented on Content.Server/DeltaV/Humanoid/Systems/LoadHumanoidSystem.cs
> +        var mind = mindComponent.Mind;
Thats fair, will do that instead

2023-06-02 06:47 UTC, DebugOk commented on Resources/Prototypes/DeltaV/Entities/Markers/Spawners/ghost_roles.yml
> +      rules: Listen to the admins.
The spawner shouldn't be mapped in, and those are just placeholders. It can easily be changed via VV in game

2023-06-08 08:34 UTC, DebugOk commented
I rewrote it to use a custom spawner that directly spawns a character instead of spawning 2 entities and deleting one of them

2023-06-12 07:41 UTC, DEATHB4DEFEAT requested changes

2023-06-12 07:41 UTC, DEATHB4DEFEAT commented on Content.Server/Ghost/Roles/GhostRoleSystem.cs
> +        private void OnSpawnerTakeCharacter(EntityUid uid, GhostRoleCharacterSpawnerComponent component, ref TakeGhostRoleEvent args)
should go in the DeltaV namespace, everything from this system used in this function is public

2023-06-12 07:41 UTC, DEATHB4DEFEAT commented on Content.Server/Ghost/Roles/GhostRoleSystem.cs
> +                .SpawnPlayerMob(coordinates: Transform(uid).Coordinates, profile: character, entity: null, job: null, station: null);
does something like this not work? it's weird defining each variable to assign to
```suggestion
                .SpawnPlayerMob(Transform(uid).Coordinates, character, null, null, null);
```

2023-06-12 08:24 UTC, DebugOk commented on Content.Server/Ghost/Roles/GhostRoleSystem.cs
> +        private void OnSpawnerTakeCharacter(EntityUid uid, GhostRoleCharacterSpawnerComponent component, ref TakeGhostRoleEvent args)
Except GhostRoleComponent, which has an access restriction

2023-06-14 06:52 UTC, DEATHB4DEFEAT approved these changes
I think I meant to approve this earlier, I looked at it all already, 👍

2023-06-14 11:38 UTC, merged