Mafia Clothing, Typewriter, Vest Resprites (AKA Drip Update Pt. 1)
DeltaV-Station/Delta-v-Legacy pull request #54
Opened 2023-06-02 13:59 UTC by TadJohnson00

## About the PR

Added various mafia items, including suits, fedoras, and flat caps. Added Typewriter SMG, Viper (wood grips), and snubbed .45 revolver. Additionally resprited kevlar/web vests.

**Media**
![image](https://github.com/DeltaV-Station/Delta-v/assets/120885811/e5b6c829-720d-406c-bd3e-8db865b14f38)
![image](https://github.com/DeltaV-Station/Delta-v/assets/120885811/88fd7dec-2fae-4cde-b219-6154dc45586d)
![image](https://github.com/DeltaV-Station/Delta-v/assets/120885811/87772788-4bce-458f-b323-0482e51b8521)
![image](https://github.com/DeltaV-Station/Delta-v/assets/120885811/da952887-f896-4155-b38b-ca4c9538d6aa)
![image](https://github.com/DeltaV-Station/Delta-v/assets/120885811/7c055b47-53d5-49e4-b30d-5e6380749c32)

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: added various mafia-related clothes, the Typewriter SMG, a snubnosed .45, and a few other tidbits.
- tweak: resprited vests (kevlar, web, flak) to look a little nicer.

2023-06-03 10:39 UTC, TadJohnson00 commented
Okay, dunno what that error is, but it oughta work fine I reckon.

2023-06-04 15:28 UTC, DebugOk commented
> Okay, dunno what that error is, but it oughta work fine I reckon.

It's unrelated. I'll rerun the tests

2023-06-04 18:52 UTC, TadJohnson00 commented
Ay, a greentext! Love to see it.

2023-06-05 09:47 UTC, DebugOk requested changes

2023-06-05 09:47 UTC, DebugOk commented on Resources/Prototypes/DeltaV/Entities/Objects/Weapons/Guns/SMGs/smgs.yml
> +  description: A modern take on the classic design that made the 2120s roar. Types .35 auto ammo.
Have we even established a date that everything takes place on? I'm not sure if these sorts of things are mentioned anywhere else, but it might be good to sort that out first.

2023-06-05 09:48 UTC, DebugOk commented on Resources/Prototypes/DeltaV/Entities/Objects/Weapons/Guns/SMGs/smgs.yml
> +  description: A modern take on the classic design that made the 2120s roar. Types .35 auto ammo.
Not saying it should be removed fully, just that there should be some discussion about this. Unless there are dates mentioned elsewhere in descriptions, if thats the case feel free to let me know and I'll approve it

2023-06-05 10:45 UTC, TadJohnson00 commented on Resources/Prototypes/DeltaV/Entities/Objects/Weapons/Guns/SMGs/smgs.yml
> +  description: A modern take on the classic design that made the 2120s roar. Types .35 auto ammo.
It's a reference to the original Tommy gun's nickname "the gun that made the '20s roar". And, as we all know, there was one S. Asshole Esq. in the year 2125, causing wanton carnage - so I wanted to tie it into that.

That being said, I'll change the description to something more ambiguous. I wouldn't even know who I would ask for definitive answers about dates and continuity, but if you happen to be able to get some, then give me a yell and I can change it in a later PR.

2023-06-05 10:46 UTC, DebugOk commented on Resources/Prototypes/DeltaV/Entities/Objects/Weapons/Guns/SMGs/smgs.yml
> +  description: A modern take on the classic design that made the 2120s roar. Types .35 auto ammo.
It's not something that exists yet afaik, and we'd probably just need to discuss it along with some other lore that was being worked on.

2023-06-05 10:51 UTC, TadJohnson00 commented on Resources/Prototypes/DeltaV/Entities/Objects/Weapons/Guns/SMGs/smgs.yml
> +  description: A modern take on the classic design that made the 2120s roar. Types .35 auto ammo.
It's been changed. Lore update when

2023-06-05 10:53 UTC, DebugOk approved these changes

2023-06-05 11:23 UTC, merged