Added Synthetic and Inactive blood
DeltaV-Station/Delta-v-Legacy pull request #87
Opened 2023-07-17 02:02 UTC by CodedCrow

## About the PR
Added synthetic blood, and inactive blood

Inactive blood: While it does count as food towards arachnee it also drains them of some asphyxiation to discourage them from doing so. 
The recipe is 10 carbon, 10 hydrogen, 10 iron, 1 plasma for 25 inactive blood. 
Because its a chemical it can be turned into pills and added to foods.

Synthetic blood: Similar to blood in most aspects but if digested by an arachnee it only creates half the Omnizine.
The recipe is 1 Inactive blood and 1 oxygen for 1 Synthetic blood.
It can also be turned into food and pills, this allows arachnee to have a large supply to food on their person and thus a large supply of Omnizine. 

**Media**
Crafting the recipe:
https://github.com/DeltaV-Station/Delta-v/assets/114866135/e40fc7a4-e2a0-498c-ba78-8a341b4c2465

And here's a short video of me after ingesting it.
https://github.com/DeltaV-Station/Delta-v/assets/114866135/aaa4d136-bbef-4dca-b762-b3c8bba06d95

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: CodedCrow
- add: Added Inactive blood and its crafting recipe
- add: Added Synthetic blood and its crafting recipe

2023-07-17 22:51 UTC, DEATHB4DEFEAT requested changes

2023-07-17 22:51 UTC, DEATHB4DEFEAT commented on Resources/Locale/en-US/reagents/meta/biological.ftl
> +reagent-desc-inactiveblood = Synthetic blood without the oxygen, causes asphyxiation if drank by an Arachnee
```suggestion
reagent-desc-inactiveblood = Synthetic blood without the oxygen, causes asphyxiation if drank by an Arachne
```

2023-07-17 22:51 UTC, DEATHB4DEFEAT commented on Resources/Locale/en-US/reagents/meta/biological.ftl
> +reagent-desc-syntheticblood = Synthetic blood, a cruetly free alternative for Arachnees. Originally Developped by Lia Rogers.
```suggestion
reagent-desc-syntheticblood = Synthetic blood, a cruelty free alternative for Arachne. Originally Developed by Lia Rogers.
```

2023-07-17 22:51 UTC, DEATHB4DEFEAT commented on Resources/Prototypes/Recipes/Reactions/chemicals.yml
> +    InactiveBlood: 25
```suggestion
    Hydrogen:
      amount: 1
    Carbon:
      amount: 1
    Iron:
      amount: 1
    Plasma:
      amount: 0.1
  products:
    InactiveBlood: 2.5
```

2023-07-17 22:51 UTC, DEATHB4DEFEAT commented on Resources/Prototypes/Recipes/Reactions/chemicals.yml
> +    InactiveBlood: 25
I think the plasma would be better as a catalyst

2023-07-17 22:59 UTC, CodedCrow commented on Resources/Prototypes/Recipes/Reactions/chemicals.yml
> +    InactiveBlood: 25
We discussed it, and the reasoning behind the choice was to give cargo more work to do. Blood also has plasma in it; not the same kind of plasma, but plasma nontheless. It was also added to make this less overall powerful: we still want Arachne to have to find their food, not just mass produce it in a chem lab.

2023-07-17 23:27 UTC, DEATHB4DEFEAT approved these changes, later dismissed

2023-07-21 22:31 UTC, DebugOk commented on Resources/Prototypes/Reagents/biological.yml
>    id: Fat
Linter is failing because you removed the `- type: reagent` here

2023-07-21 22:33 UTC, CodedCrow reviewed
Thank you for the help

2023-07-26 15:31 UTC, DebugOk approved these changes
Looks good enough

2023-07-26 15:32 UTC, merged