Trait addition: Alcoholic, German, Stutter
DeltaV-Station/Delta-v-Legacy pull request #88
Opened 2023-07-17 06:00 UTC by moonsky70

… and siezures), German (accent trait), and Stutter (minor version of built-in shutter)

## About the PR

Adds three traits to the trait system. Some changes made to traits.ftl and disabilities.yml that may conflict with other changes.

**Media**

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added German trait - replaces some characters & words
- add: Added Stutter trait - adds a light stutter to the beginning of some words
- add: Added Alcoholic trait - requires drinking alcohol every 3-5 minutes to stave off tremors and siezures

![image](https://github.com/DeltaV-Station/Delta-v/assets/14364028/3a808d24-621d-4ba9-bd65-8dc4671acdbd)
![image](https://github.com/DeltaV-Station/Delta-v/assets/14364028/dd09b0f4-6a7b-400f-b853-1662133a8e9d)
![image](https://github.com/DeltaV-Station/Delta-v/assets/14364028/a2943888-1849-470a-8da8-aeb0dc335ab6)
![image](https://github.com/DeltaV-Station/Delta-v/assets/14364028/352e5047-fc74-434e-95f5-7a094d497ccf)

2023-07-17 22:39 UTC, DEATHB4DEFEAT requested changes

2023-07-17 22:39 UTC, DEATHB4DEFEAT commented on Content.Server/Speech/EntitySystems/GermanAccentSystem.cs
> +        };
I believe there's a system for doing this which uses locale

2023-07-17 22:39 UTC, DEATHB4DEFEAT commented on Content.Server/Traits/Assorted/AlcoholismSystem.cs
> +        foreach(var player in _player.GetAllPlayerData())
use a query for the component

2023-07-17 22:39 UTC, DEATHB4DEFEAT commented on Content.Server/Traits/Assorted/AlcoholismSystem.cs
this should be made into a generic addiction system

2023-07-17 22:39 UTC, DEATHB4DEFEAT commented on Content.Shared/Traits/Assorted/AlcoholicComponent.cs
> +public sealed class AlcoholicComponentState : ComponentState
use the automatic state generation tag on the component instead of this and a system
I dont remember the exact name, I believe PDA uses it if you want an example

2023-07-17 22:39 UTC, DEATHB4DEFEAT commented on Content.Client/Traits/AlcoholismSystem.cs
why's this here

2023-07-18 20:06 UTC, moonsky70 commented on Content.Server/Speech/EntitySystems/GermanAccentSystem.cs
> +        };
I'll look into this! This system is based off of the skeleton's accent system, which replaces words in a pretty similar way. I didn't see locale used anywhere in the existing accent components, but I will go ahead and search that down <3

2023-07-18 20:07 UTC, moonsky70 commented on Content.Server/Traits/Assorted/AlcoholismSystem.cs
> +        foreach(var player in _player.GetAllPlayerData())
I'm assuming this is AllEntityQuery? I had no idea this was a thing, thank you! I'll go ahead and switch this over. I'm assuming that this will query entities other than players, which would make it slightly more expensive but also allow it to be used universally, and that sounds good.

2023-07-18 20:21 UTC, moonsky70 commented on Content.Server/Traits/Assorted/AlcoholismSystem.cs
Are you thinking just changing this to apply to any chemicals in the chemstream, rather than just ethanol? Unfortunately, while we discussed adding tobacco/marijuana dependency, currently cigarettes are purely cosmetic and don't add to the chemstream.

2023-07-19 04:31 UTC, DEATHB4DEFEAT commented on Content.Server/Traits/Assorted/AlcoholismSystem.cs
> +        foreach(var player in _player.GetAllPlayerData())
There's a function for component queries, EntitySystem's EntityQueryEnumerator

2023-07-19 04:32 UTC, DEATHB4DEFEAT commented on Content.Server/Traits/Assorted/AlcoholismSystem.cs
I think cigarettes do add to the chemstream, the effects are just really weak and the amount of reagent is so low it gets processed immediately. I don't know how else the Syndicate Smokes would work.

2023-07-19 08:00 UTC, TadJohnson00 commented on Content.Server/Traits/Assorted/AlcoholismSystem.cs
Syndicate cigarettes and other smokables with chems injected into them can be used to metabolise reagents, but nicotine itself does not exist as a reagent yet, and thus most cigarettes are useless. Nonetheless, a generic addiction system would certainly open possibilities for nicotine, desoxyephedrine, and perhaps other chemicals to pose a minor long-term liability to the station crew and medical department.

2023-07-20 15:54 UTC, moonsky70 commented on Content.Client/Traits/AlcoholismSystem.cs
You know? I'm not sure. I'm still relatively unused to the component system and copied this framework over from a different trait... But alcoholism isn't processed at all clientside, so I don't really need it. Will remove xP

2023-07-20 15:57 UTC, moonsky70 commented on Content.Server/Traits/Assorted/AlcoholismSystem.cs
> +        foreach(var player in _player.GetAllPlayerData())
What's the functional difference between AllEntityQuery and simply EntityQuery? Neither of them have code summaries, though I spose I could go check how they were written to try n figure it out

2023-07-20 16:01 UTC, moonsky70 commented on Content.Server/Speech/EntitySystems/GermanAccentSystem.cs
> +        };
Any recollection of where I might find the locale-based system? I'm not finding anything in my solution or on the discords, but that doesn't mean it isn't there.

2023-07-26 15:35 UTC, DebugOk requested changes
Cant merge due to conflicts and requested changes

2023-09-09 13:23 UTC, DebugOk commented
Closing as stale

2023-09-09 13:23 UTC, closed without merging